API_KEY = 'oGkukEVTZuZdeFZAe3or8UlHCNxnWf8vEOg8c99fGC4eCvu8dRLmw7cqlGSwWcg3'
API_SECRET = 'ID7bvPsgGnqtqPyWjE3LOGyX0aUm5x3I4jFCwvm3HhKf9HYcFwTPzecVJwSt0nM9'
# Paris 
# API_KEY = 'cvUNwPiE555ZK98afNCHhZF8kz6l5sLSdKx46da7FhGpsOttvWaEYbHgufuZP6oz'
# API_SECRET = 'yg8B6ojBfIKwwvkm6vPkcgRoSm14pg0pSjPjuWcodu7Tn7HHE29Yy88FY2fEE873'

URI = 'https://api.binance.com'

L_SYMBOLS = [
'LINKBTC',
'XRPBTC',
'ADABTC',
'AIONBTC',
'ATOMBTC',
'ADABUSD',
'BTCEUR',
'ETHEUR',
'BNBEUR',
'XRPEUR',
'EURBUSD',
'SNXBTC',
'DOTBTC',
'SXPBTC',
'SXPEUR',
'SXPBNB',
'SXPBUSD',
'LINKEUR',
'DOTEUR',
'LTCEUR',
'ADAEUR',
'BETHETH',
'UNIEUR',
'ENJEUR',
'THETAEUR',
]
